#!/bin/sh

# everything is an error, every operation is logged
set -e

md="$(dirname "$0")"
. "$md/../lib.sh"
export_all_enviles

src_dir="$DIBS_DIR_SRC"
cache_dir="$DIBS_DIR_CACHE"
env_dir="$DIBS_DIR_ENV"
git_uri="${1:-"$DIBSPACK_GIT_URI"}"

[ -n "$git_uri" ] || LOGDIE 'no git URI available'

# everything is logged from now on...
[ "x$DIBSPACK_GIT_DEBUG" = "x1" ] && set -v -x

origin="${git_uri%#*}"
ref="${git_uri#*#}"
[ "x$ref" = "x$git_uri" ] && ref=
: ${ref:=master}
INFO "origin: $origin (ref: $ref)"

# ensure_prereqs are installed, most notably git should be there
arch="$(os_id)"
[ -x "$md/prereqs/$arch" ] && "$md/prereqs/$arch"

# work in $src_dir from now on
mkdir -p "$src_dir"
cd "$src_dir" || LOGDIE "unable to get into $src_dir"

fresh=no
if [ "x$DIBSPACK_GIT_REFRESH" = "x1" -a -d .git ] ; then
   c_origin="$(git remote get-url origin)"
   if [ "x$c_origin" = "x$origin" ] ; then
      git fetch origin
   else
      cleanup_dir .
      fresh=yes
   fi
else
   cleanup_dir .
   fresh=yes
fi

# if we arrived here without a .git directory, it's time to clone
[ "x$fresh" = 'xyes' ] && git clone "$origin" .

# hop on the right ref
current_ref="$(git branch | sed -n -e '/^\*/s/^..//p')"
if [ "x$ref" != "x$current_ref" ] ; then
   git checkout "$ref"
fi

if [ "x$fresh" = 'xno' ] ; then
   # if ref is a branch there's the possibility of an update
   if git branch | grep "^..$ref\$" >/dev/null 2>&1 ; then
      git merge "origin/$ref"
   fi
fi
