#!/bin/sh

main() {
   set -e
   . "$(dirname "$0")/lib.sh"

   export_all_enviles_from . $EXPORTED_VARS

   # parse *these* options
   local work_dir os step
   parse_opts "$@"

   : ${os:="$(os_id)"}
   local program="$work_dir/prereqs/$os"
   [ -n "$step" ] && program="$program.$step"

   # run
   "$program" "$@"
}

parse_opts() {
   local optname optval
   os="$DIBS_OS"
   step="$DIBS_STEP"
   work_dir="${PACK_WORK_DIR:-"$DIBS_DIR_SRC"}"
   while [ "$#" -gt 0 ] ; do
      optname="$1"
      shift
      case "$optname" in
         (--os)
            [ "$#" -gt 0 ] || LOGDIE "no value for option $optname"
            os="$1"
            shift
            ;;
         (-s|--step)
            [ "$#" -gt 0 ] || LOGDIE "no value for option $optname"
            step="$1"
            shift
            ;;
         (-w|--work-dir)
            [ "$#" -gt 0 ] || LOGDIE "no value for option $optname"
            work_dir="$1"
            shift
            ;;
         (*)
            LOGDIE "unknown option $optname"
            ;;
      esac
   done
}

main "$@"
exit "$?"
