#!/bin/sh
set -e
. "$(dirname "$0")/lib.sh"

src_dir="$1"
step="${4:-"$DIBSPACK_STEP"}"
[ -n "$step" ] || LOGDIE "step parameter is unknown"

arch="${DIBSPACK_PREREQS_ARCH:-"$(architecture)"}"
program="$src_dir/prereqs/$arch.$step"

# run
"$program" "$@"
