#!/bin/sh
set -e
md="$(dirname "$0")"
. "$md/../lib.sh"
export_all_enviles

procfile_runner="${DIBSPACK_PROCFILE_RUNNER:-"/procfilerun"}"
cp "$md/procfilerun" "$procfile_runner"
chmod +x "$procfile_runner"

export PROCFILE_SPEC="${DIBSPACK_PROCFILE_SPEC:-"/app/Procfile"}"
export PROCFILE_DEFAULT="${DIBSPACK_PROCFILE_DEFAULT:-"web"}"
dump_env PROCFILE_SPEC PROCFILE_DEFAULT >"${procfile_runner}rc"
