#!/bin/sh
. "$(dirname "$0")/vars"
cp "$(dirname "$0")/procfilerun" "$PROCFILE_RUNNER"
chmod +x "$PROCFILE_RUNNER"
"$(dirname "$0")/../lib.sh" dump_env PROCFILE_SPEC PROCFILE_DEFAULT \
   >"${PROCFILE_RUNNER}rc"
