#!/bin/sh

script="$(readlink -f "$0")"
scriptdir="$(dirname "$script")"
basedir="$(dirname "$scriptdir")"

. "$basedir/lib.sh"
export_all_enviles

prereqs_dir="$DIBS_DIR_SRC"
[ -z "PREREQS_DIR" ] || prereqs_dir="$prereqs_dir/$PREREQS_DIR"

. /etc/os-release
packman=''
case "$ID" in
   (alpine)
      packman='apk'
      ;;
   (opensuse*)
      packman='zypper'
      ;;
   (debian)
      packman='apt-get'
      ;;
   (centos)
      packman='yum'
      ;;
   (*)
      printf >&2 '%s\n' "unknown OS '$ID'"
      exit 1
      ;;
esac

full_packman="$scriptdir/$packman"
[ "$#" -eq 0 ] || "$full_packman" "$@"
"$full_packman" -f "$prereqs_dir/prereqs.$packman"
