#!/bin/sh
exec 1>&2
set -e

script="$(readlink -f "$0")"
scriptdir="$(dirname "$script")"
basedir="$(dirname "$scriptdir")"

. "$basedir/lib.sh"
export_all_enviles

prereqs_dir="$DIBS_DIR_SRC"
[ -z "PREREQS_DIR" ] || prereqs_dir="$prereqs_dir/$PREREQS_DIR"

. /etc/os-release
packman=''
case "$ID" in
   (alpine)
      packman='apk'
      ;;
   (opensuse*)
      packman='zypper'
      ;;
   (debian)
      packman='apt-get'
      ;;
   (centos)
      packman='yum'
      ;;
   (*)
      printf >&2 '%s\n' "unknown OS '$ID'"
      exit 1
      ;;
esac

full_packman="$scriptdir/$packman"
target_list="$prereqs_dir/prereqs.$packman"
target_script="$target_list.sh"
if [ -x "$target_script" ] ; then
   "$target_script" "$@"
elif [ "$#" -gt 0 ] ; then
   "$full_packman" "$@"
fi
if [ -r "$target_list" ] ; then
   "$full_packman" -f "$prereqs_dir/prereqs.$packman"
fi
